export const  REGISTER_INSTRUCTORS = 'api/Auth/register-instructor'
export const  REGISTER_STUDENTS = 'api/Auth/register-student'
export const  LOGIN = 'api/Auth/login'
export const FORGET_PWD = 'api/Auth/forgot-password'
export const RESEND_EMAIL = 'api/Auth/resend-email-confirmation'