export const  REGISTER_INSTRUCTORS = 'Auth/register-instructor'
export const  REGISTER_STUDENTS = 'Auth/register-student'
export const  LOGIN = 'Auth/login'
export const FORGET_PWD = 'Auth/forgot-password'
export const RESEND_EMAIL = 'Auth/resend-email-confirmation'
export const REFRESH_TOKEN = 'Auth/refresh-token'
export const  REVOKE_TOKEN = 'Auth/revoke-token'
