export const ACTION_TYPES = {
    SET_FIELD: 'SET_FIELD',
    SET_VALIDATY: 'SET_VALIDATY',
    SET_FOCUS: 'SET_FOCUS',
    SET_SUCCESS: 'SET_SUCCESS',
    SET_ERROR: 'SET_ERROR',
    SET_LOADING: 'SET_LOADING',
}